
// Auth
export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN'
export const SIGN_IN_USER_STARTED = 'SIGN_IN_USER_STARTED'
export const SIGN_IN_USER_FAILED = 'SIGN_IN_USER_FAILED'
export const SIGN_IN_USER_SUCCESS = 'SIGN_IN_USER_SUCCESS'

// Submissions
export const SET_SUBMISSIONS = 'SET_SUBMISSIONS'
export const ERROR_SUBMISSIONS = 'ERROR_SUBMISSIONS'

